### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by wdfaESfaef** [NekoyaHouse/nsm#2]
1.2.0版本的YSM似乎从模型加载到解密再到渲染完全用c++写的，想用java从中间截获几乎不可能
而且据作者说新版本的.ysm文件内不包含模型的原始json文件
目前想要破解新版本的模型应该只能去研究ysm-core.dll里是怎么写的了

**Comment by hexadecimal233** [comment]
等fabric更新
我这就去催更（

**Comment by wdfaESfaef** [comment]
依我判断，除非有大量用手机或ARM架构设备的人反馈无法运行，否则应该不会对目前的解密有任何修改，而forge版不修改的前提下，为了保证模型的通用性，fabric版也必然用同样的解密方法

**Comment by hexadecimal233** [comment]
> 依我判断，除非有大量用手机或ARM架构设备的人反馈无法运行，否则应该不会对目前的解密有任何修改，而forge版不修改的前提下，为了保证模型的通用性，fabric版也必然用同样的解密方法

进群说吧
279144722

**Comment by rainbowflesh** [comment]
弃坑了么, 群搜不到了
